version: '3.5' 

services: 
    my_first_volume_exercise:  
      image: devopsdockeruh/first_volume_exercise
      build: . 

      volumes: 
        - ./logs.txt:/usr/app/logs.txt
      container_name: first_volume_exercise
      