version: '3.5' 

services: 
    backend:  
      image: backendi
      build: .
      ports: 
        - 8000:8000
      environment:
        - REDIS=redis
        - DB_USERNAME=maa
        - DB_PASSWORD=alas_ana
        - DB_HOST=db

      depends_on:
        - db

    frontend:  
      image: frontendi
      build: .
      ports: 
        - 5000:5000

    redis:  
      image: redis
      container_name: cache-for-redis
      restart: unless-stopped
      ports: 
        - 6379:6379

    db:
      image: postgres
      restart: unless-stopped
      container_name: db-postgres
      environment:
        - POSTGRES_USER=maa
        - POSTGRES_PASSWORD=alas_ana
      volumes:
        - database:/var/lib/postgresql/data

volumes:
  database:
  