version: '3.5' 

services: 
    backend:  
      image: backendi
      build: ./backendhere
      ports: 
        - 8000:8000

    frontend:  
      image: frontendi
      build: ./frontendhere
      ports: 
        - 5000:5000
